import Head from "next/head";
import Header from "../../../public/Components/Header";
import Footer from "../../../public/Components/Footer";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import toast from "react-hot-toast";

export default function Register() {
  const [formData, setFormData] = useState({
    email: "",
    username: "",
    password: "",
    confirmPassword: "",
    id: "",
  });

  const route = useRouter();

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const createUser = async () => {
      const res = await fetch("/api/users/register", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ ...formData, role: "volunteer" }),
      });

      if (!res.ok) {
        toast.error("Error, Try again");
      }

      const responseData = await res.json();
      if (responseData.data) {
        route.push("/login");
      } else {
        toast.error("Error, Try again");
      }
    };

    if (
      formData.username &&
      formData.email &&
      formData.password == formData.confirmPassword
    )
      createUser();
  };
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by react" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <div className="container-register">
          <h2>Volunteer Register</h2>
          <form id="registerForm" onSubmit={handleSubmit}>
            <input
              type="email"
              id="email"
              name="email"
              placeholder="Email"
              required
              value={formData.email}
              onChange={handleChange}
            />
            <input
              type="text"
              id="username"
              name="username"
              placeholder="Username"
              required
              value={formData.username}
              onChange={handleChange}
            />
            <input
              type="text"
              id="id"
              name="id"
              placeholder="ID or VAT"
              required
              value={formData.id}
              onChange={handleChange}
            />
            <input
              type="password"
              id="password"
              name="password"
              placeholder="Password"
              required
              value={formData.password}
              onChange={handleChange}
            />
            <input
              type="password"
              id="passwordConf"
              name="confirmPassword"
              placeholder="Confirm Password"
              required
              value={formData.confirmPassword}
              onChange={handleChange}
            />

            <div style={{ textAlign: "start", marginBottom: 20 }}>
              <p style={{ marginBottom: 10, fontWeight: 600 }}>
                Upload Documents
              </p>
              <input type="file" id="file" name="file" onChange={(e) => {}} />
            </div>

            <input type="submit" value="Register" />
          </form>
          <p>
            Already have an account? <Link href="/login">Login here</Link>
          </p>

          <p>
            <Link href="/register/farmer">Register as Farmer</Link>
          </p>
        </div>
        <Footer />
      </main>
    </>
  );
}
