/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Header from "../../public/Components/Header";
import Footer from "../../public/Components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Networks For Growing Berries</title>
        <meta name="description" content="Generated by react" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <div className="container">
          <div className="rectangle">
            <p>More than volunteering</p>
            <p>Join us for meaningful volunteering</p>
            <p>
              Experiences that connect a wide variety of populations to farmers
              who need help
            </p>
            <a href="#" className="button">
              LEARN MORE
            </a>
          </div>

          <h2 className="selection-heading">SELECTION BY REGION</h2>
          <div className="region-container">
            <div className="region">
              CENTRAL
              <p>100K+ Opportunities</p>
            </div>
            <div className="region">
              NORTH
              <p>200K+ Opportunities</p>
            </div>
            <div className="region">
              WEST
              <p>100K+ Opportunities</p>
            </div>
          </div>

          <h2 className="next-to-you">NEXT TO YOU</h2>
          <div className="farm-container">
            <a href="farm1-page.html" className="farm-link">
              <div className="farm">
                <img src="/Images/a.jpeg" alt="Farm 1" />
                <p>משק רצון ממושב עזריאל</p>

                <div className="rating">
                  <input type="radio" id="star1" name="rating1" value="1" />
                  <label htmlFor="star1">&#9733;</label>
                  <input type="radio" id="star2" name="rating1" value="2" />
                  <label htmlFor="star2">&#9733;</label>
                  <input type="radio" id="star3" name="rating1" value="3" />
                  <label htmlFor="star3">&#9733;</label>
                  <input type="radio" id="star4" name="rating1" value="4" />
                  <label htmlFor="star4">&#9733;</label>
                  <input type="radio" id="star5" name="rating1" value="5" />
                  <label htmlFor="star5">&#9733;</label>
                </div>
              </div>
            </a>

            <a href="farm2-page.html" className="farm-link">
              <div className="farm">
                <img src="/Images/R.jpeg" alt="Farm 2" />
                <p>משק חקלאי במושב רוויה</p>

                <div className="rating">
                  <input type="radio" id="star6" name="rating2" value="1" />
                  <label htmlFor="star6">&#9733;</label>
                  <input type="radio" id="star7" name="rating2" value="2" />
                  <label htmlFor="star7">&#9733;</label>
                  <input type="radio" id="star8" name="rating2" value="3" />
                  <label htmlFor="star8">&#9733;</label>
                  <input type="radio" id="star9" name="rating2" value="4" />
                  <label htmlFor="star9">&#9733;</label>
                  <input type="radio" id="star10" name="rating2" value="5" />
                  <label htmlFor="star10">&#9733;</label>
                </div>
              </div>
            </a>

            <a href="farm3-page.html" className="farm-link">
              <div className="farm">
                <img src="/Images/tal.jpg" alt="Farm 3" />
                <p>משק טל נעורים</p>

                <div className="rating">
                  <input type="radio" id="star11" name="rating3" value="1" />
                  <label htmlFor="star11">&#9733;</label>
                  <input type="radio" id="star12" name="rating3" value="2" />
                  <label htmlFor="star12">&#9733;</label>
                  <input type="radio" id="star13" name="rating3" value="3" />
                  <label htmlFor="star13">&#9733;</label>
                  <input type="radio" id="star14" name="rating3" value="4" />
                  <label htmlFor="star14">&#9733;</label>
                  <input type="radio" id="star15" name="rating3" value="5" />
                  <label htmlFor="star15">&#9733;</label>
                </div>
              </div>
            </a>
          </div>

          <h2 className="all-opportunities">ALL THE OPPORTUNITIES</h2>
          <div className="opportunity-container">
            <div className="opportunity">
              <img src="/Images/PI.jpg" alt="Opportunity 1" />
              <div className="opportunity-text">
                <p className="title">
                  South Activities in the <br />
                  Pineapple Greenhouse
                </p>
                <p className="description">
                  Dear volunteers, I am Eitan <br />
                  Second generation <br />
                  of farmers in the south
                </p>
              </div>
            </div>

            <div className="opportunity">
              <img src="opportunity2.jpg" alt="Opportunity 2" />
              <p>Opportunity 2</p>
            </div>

            <div className="opportunity">
              <img src="opportunity3.jpg" alt="Opportunity 3" />
              <p>Opportunity 3</p>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
}
