import Head from "next/head";
import Header from "../../public/Components/Header";
import Footer from "../../public/Components/Footer";
import { useState } from "react";
import Link from "next/link";

export default function Login() {
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Add logic to submit the form data to the login endpoint
    console.log(formData);
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by react" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <div className="container-login">
          <h2>Login</h2>
          <form id="loginForm" onSubmit={handleSubmit}>
            <input
              type="email"
              id="email"
              name="email"
              placeholder="Email"
              required
              className="form-input"
              onChange={handleChange}
            />
            <input
              type="password"
              id="password"
              name="password"
              placeholder="Password"
              required
              className="form-input"
              onChange={handleChange}
            />
            <input type="submit" value="Login" className="submit-button" />
          </form>
          <p>
            Don&apos;t have an account?{" "}
            <Link href="/register" passHref>
              Register here
            </Link>
          </p>
        </div>
        <Footer />
      </main>
    </>
  );
}
